fix action

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -31,10 +31,10 @@ jobs:
           ssh ${{ secrets.EC2_USER}}@${{ secrets.EC2_HOST}} '
           export NVM_DIR=$"HOME/.nvm"
           if [ -s "$NVM_DIR/nvm.sh" ]; then
-          . "$NVM_DIR/nvm.sh"
+              . "$NVM_DIR/nvm.sh"
           else
-          echo "nvm,sh not found"
-          exit 1
+              echo "nvm,sh not found"
+              exit 1
           fi
 
           nvm -v'
