test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -105,89 +105,90 @@ jobs:
 
         # mongodb 는 -P를 띄어씀
 
-  # deploy_front:
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Checkout repository
-  #       uses: actions/checkout@v4
+  deploy_front:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-  #     - name: Add SSH key
-  #       uses: webfactory/ssh-agent@v0.5.4
-  #       with:
-  #         ssh-private-key: ${{secrets.EC2_KEY}}
+      - name: Add SSH key
+        uses: webfactory/ssh-agent@v0.5.4
+        with:
+          ssh-private-key: ${{secrets.EC2_KEY}}
 
-  #     - name: Ensure SSH directory exists
-  #       run: |
-  #         mkdir -p ~/ .ssh
-  #         chmod 700 ~/ .ssh
+      - name: Ensure SSH directory exists
+        run: |
+          mkdir -p ~/ .ssh
+          chmod 700 ~/ .ssh
 
-  #     - name: Add SSH known hosts
-  #       run: SSH-keyscan -H ${{secrets.EC2_HOST}} >> ~/.ssh/known_hosts
+      - name: Add SSH known hosts
+        run: SSH-keyscan -H ${{secrets.EC2_HOST}} >> ~/.ssh/known_hosts
 
-  #     - name: Install Dependencies of Front
-  #       working-directory: ./quert-test
+      - name: Install Dependencies of Front
+        working-directory: ./quert-test
 
-  #     - name: Build Front
-  #       working-directory: ./query-test
-  #       run: npm run build
+      - name: Build Front
+        working-directory: ./query-test
+        run: npm run build
 
-  #     - name: Copy files to EC2
-  #       run: |
-  #         ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "rm -rf /var/www/front"
-  #         ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "mkdir -p /var/www/front"
-  #         rsync -avz -e "ssh" ./query-test/build/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/front
+      - name: Copy files to EC2
+        run: |
+        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
+            rm -rf /var/www/front
+            mkdir /var/www/front'
+          rsync -avz -e "ssh" ./server/build/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/front
 
-  #     - name: Restart Nginx
-  #       run: ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'sudo service nginx restart'
+      - name: Restart Nginx
+        run: ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'sudo service nginx restart'
 
-  # deploy_back:
-  #   runs-on: ubuntu-latest
-  #   needs:
-  #     - test_node
-  #     - test_mysql
-  #     - test_mongo
-  #   steps:
-  #     - name: checkout repository
-  #       uses: actions/checkout@v4
+  deploy_back:
+    runs-on: ubuntu-latest
+    needs:
+      - test_node
+      - test_mysql
+      - test_mongo
+    steps:
+      - name: checkout repository
+        uses: actions/checkout@v4
 
-  #     - name: Add SSH key
-  #       uses: webfactory/ssh-agent@v0.5.4
-  #       with:
-  #         ssh-private-key: ${{ secrets.EC2_KEY }}
+      - name: Add SSH key
+        uses: webfactory/ssh-agent@v0.5.4
+        with:
+          ssh-private-key: ${{ secrets.EC2_KEY }}
 
-  #     - name: Ensure SSH directory exists
-  #       run: |
-  #         mkdir -p ~/.ssh
-  #         chmod 700 ~/.ssh
+      - name: Ensure SSH directory exists
+        run: |
+          mkdir -p ~/.ssh
+          chmod 700 ~/.ssh
 
-  #     - name: Add SSH known hosts
-  #       run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
+      - name: Add SSH known hosts
+        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
 
-  #     - name: Install Dependencies of Back
-  #       working-directory: ./server
-  #       run: npm i
+      - name: Install Dependencies of Back
+        working-directory: ./server
+        run: npm i
 
-  #     - name: Build Back
-  #       working-directory: ./server
-  #       run: npx tsc
+      - name: Build Back
+        working-directory: ./server
+        run: npx tsc
 
-  #     - name: Copy Files to EC2
-  #       run: |
-  #         ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
-  #           rm -rf /var/www/backend
-  #           mkdir /var/www/backend'
-  #         rsync -avz -e "ssh" ./server/build/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/backend
-  #         rsync -avz -e "ssh" ./server/package.json ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/backend/package.json
-  #         ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
-  #           export NVM_DIR="$HOME/.nvm"
-  #           if [ -s "$NVM_DIR/nvm.sh" ]; then
-  #             . "$NVM_DIR/nvm.sh"
-  #           else
-  #             echo "nvm.sh not found"
-  #             exit 1
-  #           fi
+      - name: Copy Files to EC2
+        run: |
+          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
+            rm -rf /var/www/backend
+            mkdir /var/www/backend'
+          rsync -avz -e "ssh" ./server/build/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/backend
+          rsync -avz -e "ssh" ./server/package.json ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/backend/package.json
+          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
+            export NVM_DIR="$HOME/.nvm"
+            if [ -s "$NVM_DIR/nvm.sh" ]; then
+              . "$NVM_DIR/nvm.sh"
+            else
+              echo "nvm.sh not found"
+              exit 1
+            fi
 
-  #           nvm use --lts
-  #           cd /var/www/backend
-  #           npm i --production'
-  #           ${{ secrets.SERVER_ENV }}
+            nvm use --lts
+            cd /var/www/backend
+            npm i --production'
+            ${{ secrets.SERVER_ENV }}
