fix action

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -27,15 +27,15 @@ jobs:
         run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
 
       - name: test node
-        run: ssh ${{ secrets.EC2_USER}}@${{ secrets.EC2_HOST}} '
+        run: |
+          ssh ${{ secrets.EC2_USER}}@${{ secrets.EC2_HOST}} '
           export NVM_DIR=$"HOME/.nvm"
           if [ -s "$NVM_DIR/nvm.sh" ]; then
-              . "$NVM_DIR/nvm.sh"
+          . "$NVM_DIR/nvm.sh"
           else
-              echo "nvm,sh not found"
-              exit 1
+          echo "nvm,sh not found"
+          exit 1
           fi
 
-        nvm -v'
+          nvm -v'
         # run: ssh ${{ secrets.EC2_USER}}@${{ secrets.EC2_HOST}} 'source ~/.bashrc && nvm -v'  ##---> 이전에 설치한것을 읽지 못함
-
