add server

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -141,27 +141,27 @@ jobs:
         run: ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'sudo service nginx restart'
 
   deploy_back:
-    runs-on: ubuntu-lastst
+    runs-on: ubuntu-latest
     needs:
       - test_node
       - test_mysql
       - test_mongo
     steps:
-      - name: Checkout repository
+      - name: checkout repository
         uses: actions/checkout@v4
 
       - name: Add SSH key
-       uses: webfactory/ssh-agent@v0.5.4
+        uses: webfactory/ssh-agent@v0.5.4
         with:
-         ssh-private-key: ${{secrets.EC2_KEY}}
+          ssh-private-key: ${{ secrets.EC2_KEY }}
 
       - name: Ensure SSH directory exists
         run: |
-          mkdir -p ~/ .ssh
-          chmod 700 ~/ .ssh
+          mkdir -p ~/.ssh
+          chmod 700 ~/.ssh
 
       - name: Add SSH known hosts
-        run: SSH-keyscan -H ${{secrets.EC2_HOST}} >> ~/.ssh/known_hosts
+        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
 
       - name: Install Dependencies of Back
         working-directory: ./server
@@ -171,22 +171,22 @@ jobs:
         working-directory: ./server
         run: npx tsc
 
-      - name: Copy files to EC2
+      - name: Copy Files to EC2
         run: |
-          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "rm -rf /var/www/backend"
-          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "mkdir -p /var/www/backend"
-          sync -avz -e "ssh" ./server/build ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/front
-          sync -avz -e "ssh" ./server/package.json ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/front
-          ssh ${{ secrets.EC2_USER}}@${{ secrets.EC2_HOST}} '
-          export NVM_DIR="$HOME/.nvm"
-          if [ -s "$NVM_DIR/nvm.sh" ]; then
-            . "$NVM_DIR/nvm.sh"
-          else
-            echo "nvm.sh not found"
-            exit 1
-          fi
+          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
+            rm -rf /var/www/backend
+            mkdir /var/www/backend'
+          rsync -avz -e "ssh" ./server/build/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/backend
+          rsync -avz -e "ssh" ./server/package.json ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/backend/package.json
+          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
+            export NVM_DIR="$HOME/.nvm"
+            if [ -s "$NVM_DIR/nvm.sh" ]; then
+              . "$NVM_DIR/nvm.sh"
+            else 
+              echo "nvm.sh not found"
+              exit 1
+            fi
 
-          nvm -v
-          nvm use --lts
-          cd /var/www/backend
-          npm i --production'
+            nvm use --lts
+            cd /var/www/backend
+            npm i --production'
